// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/22/2025, 1:27:40 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/phloemus/docs/dev/Bail-ly2/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/phloemus/docs/dev/Bail-ly2/frontend/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/phloemus/docs/dev/Bail-ly2/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/phloemus/docs/dev/Bail-ly2/frontend/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/phloemus/docs/dev/Bail-ly2/frontend/src/plugins/**/*.{js,ts,mjs}","/home/phloemus/docs/dev/Bail-ly2/frontend/src/composables/**/*.{js,ts,mjs}","/home/phloemus/docs/dev/Bail-ly2/frontend/src/utils/**/*.{js,ts,mjs}","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/index.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/query/[id].vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/locataires/[id].vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/proprietes/[id].vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/admin/delete-all.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/locataires/creer.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/locataires/index.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/proprietes/creer.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/proprietes/index.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/contrats-bail/[id].vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/contrats-bail/creer.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/contrats-bail/index.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/admin/recreate-graph.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/pages/email-planifies/index.vue","/home/phloemus/docs/dev/Bail-ly2/frontend/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/phloemus/docs/dev/Bail-ly2/frontend/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/phloemus/docs/dev/Bail-ly2/frontend/src/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;