// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/22/2025, 3:36:52 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/plugins/**/*.{js,ts,mjs}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/composables/**/*.{js,ts,mjs}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/utils/**/*.{js,ts,mjs}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/pages/index.vue","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/pages/query/[id].vue","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/pages/proprietes/[id].vue","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/pages/admin/delete-all.vue","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/pages/proprietes/index.vue","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/pages/admin/recreate-graph.vue","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/pages/contrat-location/[id].vue","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;