// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/22/2025, 5:44:51 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/plugins/**/*.{js,ts,mjs}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/composables/**/*.{js,ts,mjs}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/utils/**/*.{js,ts,mjs}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/brieuc/Documents/other/perso/dev/Bail-ly2/frontend/src/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;